version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: saath-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: saath
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - saath-network

  # Node.js application
  app:
    build: .
    container_name: saath-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/saath?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - saath-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: saath-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - saath-network

volumes:
  mongodb_data:

networks:
  saath-network:
    driver: bridge 